FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=admin123
ENV DB_TYPE=sqlite
ENV GENERIC_TIMEZONE=America/Argentina/Buenos_Aires

EXPOSE 5678
